hyt:
  # 全局限流
  ratelimit:
    # 开启
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制200个请求
    limit: 200
  # IP限流
  iplimit:
    # 开启
    enable: true
    # 每1秒内
    timeout: 1000
    # 每个ip限制30个请求
    limit: 30000
  # 后台token交互方式
  token:
    # 默认为true，token将存入redis，并具有单点登录功能 设为false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间 redis模式有请求自动刷新（分钟）
    tokenExpireTime: 600000
    # 用户选择 保存登录状态/记住我 对应token过期时间（天）
    saveLoginTime: 7000
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # app应用 token交互配置
  appToken:
    # 是否开启同一平台单设备登陆（如安卓设备只允许登录一个相同账号，同时IOS设备可允许一个设备登陆）
    spl: true
    # token过期时间 有请求自动刷新（天）
    tokenExpireTime: 30
  # 使用Spring @Cacheable注解失效时间
  cache:
    # 缓存过期时间 Duration类型 D–天 H小时 M–分钟 S–秒 永久不过期设为非正值
    timeToLive: 15D
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # 腾讯位置服务key配置 腾讯位置服务官网注册添加key
  qqlbs:
    key: 你的腾讯位置服务key